package com.example.fyersapi;

import java.util.Arrays;
import java.util.List;

/**
 * Convenience class that stores FYERS-formatted symbol strings for all NIFTY 100
 * index constituents (as of mid-2025).  The format expected by FYERS is
 * "NSE:SYMBOL-EQ".
 */
public final class Nifty100Stocks {
    public static final List<String> SYMBOLS = Arrays.asList(
            // --- NIFTY 50 ---
            "NSE:ADANIENT-EQ",
            "NSE:ADANIPORTS-EQ",
            "NSE:APOLLOHOSP-EQ",
            "NSE:ASIANPAINT-EQ",
            "NSE:AXISBANK-EQ",
            "NSE:BAJAJ-AUTO-EQ",
            "NSE:BAJAJFINSV-EQ",
            "NSE:BAJFINANCE-EQ",
            "NSE:BPCL-EQ",
            "NSE:BHARTIARTL-EQ",
            "NSE:BRITANNIA-EQ",
            "NSE:CIPLA-EQ",
            "NSE:COALINDIA-EQ",
            "NSE:DIVISLAB-EQ",
            "NSE:DRREDDY-EQ",
            "NSE:EICHERMOT-EQ",
            "NSE:GRASIM-EQ",
            "NSE:HCLTECH-EQ",
            "NSE:HDFCBANK-EQ",
            "NSE:HDFCLIFE-EQ",
            "NSE:HEROMOTOCO-EQ",
            "NSE:HINDALCO-EQ",
            "NSE:HINDUNILVR-EQ",
            "NSE:ICICIBANK-EQ",
            "NSE:INFY-EQ",
            "NSE:INDIGO-EQ",
            "NSE:ITC-EQ",
            "NSE:JSWSTEEL-EQ",
            "NSE:KOTAKBANK-EQ",
            "NSE:LT-EQ",
            "NSE:M&M-EQ",
            "NSE:MARUTI-EQ",
            "NSE:NTPC-EQ",
            "NSE:ONGC-EQ",
            "NSE:POWERGRID-EQ",
            "NSE:RELIANCE-EQ",
            "NSE:SBILIFE-EQ",
            "NSE:SBIN-EQ",
            "NSE:SUNPHARMA-EQ",
            "NSE:TATACONSUM-EQ",
            "NSE:TATAMOTORS-EQ",
            "NSE:TATASTEEL-EQ",
            "NSE:TCS-EQ",
            "NSE:TECHM-EQ",
            "NSE:TITAN-EQ",
            "NSE:UPL-EQ",
            "NSE:WIPRO-EQ",
            
            // --- NIFTY Next 50 (selection) ---
            "NSE:ACC-EQ",
            "NSE:ADANIGREEN-EQ",
            "NSE:ALKEM-EQ",
            "NSE:AMBUJACEM-EQ",
            "NSE:AUROPHARMA-EQ",
            "NSE:BANDHANBNK-EQ",
            "NSE:BANKBARODA-EQ",
            "NSE:BERGEPAINT-EQ",
            "NSE:BIOCON-EQ",
            "NSE:BOSCHLTD-EQ",
            "NSE:CANBK-EQ",
            "NSE:CHOLAFIN-EQ",
            "NSE:COLPAL-EQ",
            "NSE:DABUR-EQ",
            "NSE:DLF-EQ",
            "NSE:GAIL-EQ",
            "NSE:GODREJCP-EQ",
            "NSE:HAVELLS-EQ",
            "NSE:HDFCAMC-EQ",
            "NSE:ICICIGI-EQ",
            "NSE:ICICIPRULI-EQ",
            "NSE:IRCTC-EQ",
            "NSE:LICHSGFIN-EQ",
            "NSE:LTIM-EQ",
            "NSE:MCDOWELL-N-EQ",
            "NSE:MUTHOOTFIN-EQ",
            "NSE:NAUKRI-EQ",
            "NSE:NMDC-EQ",
            "NSE:OFSS-EQ",
            "NSE:PIDILITIND-EQ",
            "NSE:SAIL-EQ",
            "NSE:SHREECEM-EQ",
            "NSE:SRF-EQ",
            "NSE:TORNTPHARM-EQ",
            "NSE:TVSMOTOR-EQ",
            "NSE:UBL-EQ",
            "NSE:VEDL-EQ",
            "NSE:VOLTAS-EQ",
            "NSE:ZEEL-EQ",
            "NSE:SIEMENS-EQ",
            "NSE:LUPIN-EQ",
            "NSE:NESTLEIND-EQ",
            "NSE:INDUSTOWER-EQ",
            "NSE:BAJAJHLDNG-EQ",
            "NSE:IDFCFIRSTB-EQ",
            "NSE:MPHASIS-EQ",
            "NSE:ADANIPOWER-EQ",
            "NSE:ATGL-EQ",
            "NSE:PFC-EQ",
            "NSE:RECLTD-EQ"
    );

    private Nifty100Stocks() {
    }
}